### ISSUE TITLE
Documentation for Thumbnail Location

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#1]
The UI expects image thumbnail to be at /thumbnail/path/**image** which is undocumented behavior (and not how Cineast by default extracts thumbnails for images)

**Comment by ppanopticon** [comment]
It actually is documented. See https://github.com/vitrivr/vitrivr-ng/wiki, section 'Configuration', last paragraph. But maybe it's too convoluted. I'll keep that in mind for the next update to the Wiki.

Also, of course, you're right that Cineast does not create this additional level of in the hierarchy. Maybe that is something we should discuss with Luca. However, it is fairly easy for the user to do this setup manually.
