### ISSUE TITLE
Number of results inconsistent between views

### ISSUE THREAD

**Issue by lucaro** [vitrivr/vitrivr-ng#109]
When segments are grouped by object, rather than shown independently, sometimes substantially fewer results are shown. I'm not sure if this is related to #108, the filtering mechanism, or something completely different.

**Comment by silvanheller** [comment]
The limit is indeed different for objects and segments. Do you have an example where elements are actually missing? Because to me this sounds like a scrolling issue

**Comment by lucaro** [comment]
It might very well be the same issue as #108, I couldn't say as I was never able to reproduce it consistently.

**Comment by silvanheller** [comment]
I'll close this as non-reproducible
