### ISSUE TITLE
Automatically build release artifacts using Github Actions

### ISSUE THREAD

**Issue by lucaro** [vitrivr/vitrivr-ng#15]
Since the last release, nobody updated the pre-built version of the UI in the github releases. Could someone have a look at this and how to prevent this in the future?

**Comment by silvanheller** [comment]
I made a PR template in 9cfb1c2df8b6d42e8a5fdb8ea8f988e2f906b155 which could fix this problem (if people use the template), i could make a corresponding one in the cineast repo for vitrivr/cineast#89

**Comment by lucaro** [comment]
I can see the benefit of having such a template for pull-requests. I do however not understand how this would help with not having pre-built artifacts after a release. A pul-request is not even a necessary step in the release workflow.

**Comment by silvanheller** [comment]
Yeah, but if we only do changes to master via PRs, this is the best way to make sure pre-builts are updated. Alternatively we delete all releases, because there is a way to download the github repo in a zip on the frontpage.

**Comment by lucaro** [comment]
I would prefer not having to require all users to build the entire stack before they can use it.

**Comment by silvanheller** [comment]
Yes, then a PR template is as far i can see the only sensible way to fix this problem. Alternatively, we could offer pre-built docker containers which we update with some CI stuff but that would require effort to develop a config UI.

**Comment by lucaro** [comment]
We can also do release atrifacts using the CI, the github api supports this if I'm not mistaken.

**Comment by silvanheller** [comment]
Yes, if anybody wants to take the time the [Travis Documentation](https://docs.travis-ci.com/user/deployment/releases/) is here

**Comment by ppanopticon** [comment]
Don't we want to use GitHub Actions instead? You can have a look at the Cottontail DB repository on how to do this.

**Comment by mittulmandhan** [comment]
Can I work on this?

**Comment by silvanheller** [comment]
@mittulmandhan sure

**Comment by mittulmandhan** [comment]
Thanks @silvanheller 
I want to join Vitrivr on slack to keep up with everyone.
I tried to join https://vitrivr.slack.com/# but getting this error:
![image](https://user-images.githubusercontent.com/24234639/113927452-22275f80-980b-11eb-8f2f-37eabc021821.png)

**Comment by silvanheller** [comment]
Feel free to join using the following invite link: join dot slack dot com /t/vitrivr/shared_invite/zt-nvy1ftl0-4S8lIahCGyoNSqe6XAPDNQ

**Comment by mittulmandhan** [comment]
Thanks @silvanheller

**Comment by magnetomax** [comment]
I was going through good first issues and found this project. There are some sections where I can contribute. 
1. We can optimize github actions by removing install angular step and use `npm run build  -- -c=production` command instead of `ng build --prod` in next step. This will remove dependency on global angular-cli and uses the dev-dependent angular-cli from project package. Also `--prod` has been deprecated.
2. Update docs to execute `npm start` instead of installing angular-cli and then executing `ng serve`. Both does the same job, but the difference is in local and global dependency.

**Comment by silvanheller** [comment]
Sounds good, feel free to open a pull request. I'll close this issue since it's been fixed some time ago, the suggested improvements are very welcome though.
