### ISSUE TITLE
Separate Object- and Segment Scoring into two interfaces

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#19]
Currently, the `FusionFunction` interface is responsible for scoring both segments and objects. Ideally, this is separated into two interfaces with an extension of the config so users can choose which scoring / fusion function to use at runtime.

**Comment by sauterl** [comment]
In the same step, we could upgrade the `ScoredPath` into a proper score container

**Comment by silvanheller** [comment]
This has been implemented
