### ISSUE TITLE
Add description to tag-retrieval

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#27]
currently, if there are two concepts with the same name but a different description (e.g. crane), they are not distinguishable by the user.

**Comment by lucaro** [comment]
I would suggest to implement this similarly to wikidata: 
![image](https://user-images.githubusercontent.com/246519/71943823-2d33b000-31c2-11ea-9142-d7ac9322fa11.png)

The tag description should already be available in the front end (in case it is available in the back end in the first place), so this should not require any API changes.
