### ISSUE TITLE
default host for websocket

### ISSUE THREAD

**Issue by lucaro** [vitrivr/vitrivr-ng#3]
It would be a desirable behavior if the host used for the websocket connection would default to whatever host the ui is currently served from, instead of having to specify it explicitly. This would be especially useful in cases where the ui is served from a machine which can be reached by different host names or through a proxy.

**Comment by silvanheller** [comment]
@lucaro can this issue be closed? The websocket host is configurable and i'm not exactly sure anymore what this issue references.

**Comment by lucaro** [comment]
The point of this issue was that the websocket host should default to whatever host the UI itself is served from, since this is the most common case. We currently always have the host explicitly set to 127.0.0.1, which causes problems in some situations. This could then be avoided.

**Comment by silvanheller** [comment]
Ok, so the concrete suggestion is removing api.host from the config
https://github.com/vitrivr/vitrivr-ng/blob/0aada92cad8da92175b80e8fc72c52c09b64b920/src/config.json#L3

and finding a way to connect to the host in the current endpoint_ws
https://github.com/vitrivr/vitrivr-ng/blob/0aada92cad8da92175b80e8fc72c52c09b64b920/src/app/shared/model/config/config.model.ts#L196

**Comment by lucaro** [comment]
Exactly. I was under the impression, that we already had a similar case in the past, although I don't remember if it was related to the websocket connection or to the thumbnails/media objects.

**Comment by silvanheller** [comment]
We had the default behavior, but this was not made explicit in the config. This is implemented & working on dev/

**Comment by lucaro** [comment]
I guess the way it was implemented before, one would just need to not set a host at all, right?

**Comment by silvanheller** [comment]
yes, i think so.
