### ISSUE TITLE
Retrieved images in the UI are blank.

### ISSUE THREAD

**Issue by cribin** [vitrivr/vitrivr-ng#43]
Dear developers,

I have set up the vitrivr stack according to the getting started tutorials. I could successfully query images via the vitrivr-ng UI , by running cineast locally as a web server on my pc. However, the retrieved images appear to be blank. I assume, this is caused by a wrong setting for the objects and thumbnail paths. 
In the attachments you will find a screenshot of the UI, the config file for vitrivr-ng and the cineast.json file.

Best,

Ribin
[vitrivir-config-files-ans-screenshot.zip](https://github.com/vitrivr/vitrivr-ng/files/5246658/vitrivir-config-files-ans-screenshot.zip)

**Comment by lucaro** [comment]
Hey,

I just had a look at the configs you attached and your thumbnail location is set to

```json
"host_thumbnails" : "thumbnails/:o/:s:x"
```

but if you are using cineast to serve thumbnails, it expects to be only given the segment id (see https://github.com/vitrivr/cineast/blob/dev/cineast-api/src/main/java/org/vitrivr/cineast/api/APIEndpoint.java#L376) If you set it to 

```json
"host_thumbnails" : "thumbnails/:s"
```

it should work, given that cineast can resolve the files correctly.

**Comment by cribin** [comment]
Hey Luca,

Sadly, the retrieved images are still blank, I assume cineast cannot resolve the files correctly(See image in the attachment). 
In my project structure, I have three folders: cineast(dev branch), cottontaildb(master branch) and vitrivr-ng(dev branch). In the cineast folder, I have two folders for the content called objects(containing my test images) and thumbnails(containing the generated thumbnails from cineast). My cineast.json file references the content folders(with serveContent set to true). The example job file also references this two folders. The vitrivr-config host properties are still the same as in the attachment above. 
Where should I place  the objects and thumbnails folder, so that the images can be resolved correctly?

Best,

Ribin
![Vitrivr-Ng-Blank-Image](https://user-images.githubusercontent.com/20424212/93739424-90e2f980-fbe8-11ea-824b-be2b3591d4c5.png)

**Comment by lucaro** [comment]
The files which are supposed to be served are resolved using the configured base path (in your case, according to your config.json `/home/cribin/Vitrivir_Local_Installation/test-images/` for the images and `/home/cribin/Vitrivir_Local_Installation/output-thumbnails/` for the generated thumbnails) and the path of the object itself, which in your example is just `185.jpg`. So there should be a file `/home/cribin/Vitrivir_Local_Installation/test-images/185.jpg` which is the input image and another file `/home/cribin/Vitrivir_Local_Installation/output-thumbnails/i_0000001_1.jpg` which is the preview. Can you verify that these files are there? They should then, according to your configuration, be served via `http://<your cineast host>/objects/i_0000001` and `http://<your cineast host>/thumbnails/i_0000001_1` respectively. If you open these URLs in your browser, do you get a response?

**Comment by cribin** [comment]
Hi Luca,

I verified that the images are indeed in the test-images folders and they can be accessed by the url. However, the thumbnail location is: /home/cribin/Vitrivir_Local_Installation/output-thumbnails/i_0000001/i_0000001_1.jpg. So how should I modify the config files?

Best,

Ribin

**Comment by lucaro** [comment]
Do you get a response in your browser when you try to access `http://<your cineast host>/objects/i_0000001` or `http://<your cineast host>/thumbnails/i_0000001_1` directly?

**Comment by cribin** [comment]
For http://<your cineast host>/objects/i_0000001 I get a response(I see the image), for http://<your cineast host>/thumbnails/i_0000001_1, I don't see the image, but receive the following window:
![Screenshot_2020-09-21 Screenshot](https://user-images.githubusercontent.com/20424212/93771389-b9391b00-fc1d-11ea-97ec-4d41512f8226.png)

**Comment by lucaro** [comment]
Interesting, so in case of the objects, the image should be shown in the detail view you used for the above screenshot, if you set the following in your ui config:
```json
"host_objects": "objects/:o"
```

I don't currently know where the thumbnail error comes from. What is the 'Raw Data' that is returned? What files are there in `/home/cribin/Vitrivir_Local_Installation/output-thumbnails/i_0000001/`?

**Comment by cribin** [comment]
I have set objects/:o in the ui config, but the image is still not visible (in the detail view).
The raw data returned is: Bad Request.
In the folder /home/cribin/Vitrivir_Local_Installation/output-thumbnails/i_0000001/, there  is an image file called: i_0000001_1.jpg.

**Comment by lucaro** [comment]
For the detail view, when you have a look at the URL the ui actually tries to load, is it the same as you previously tested manually? For the thumbnails, do you get any log output when you try to access something via http?

**Comment by cribin** [comment]
The urls are not the same.The url in the ui is http://localhost:4200/objects/i_0000001, but the one I used was http://localhost:4567/objects/i_0000001 (cineast is on port 4567).

**Comment by lucaro** [comment]
Ah, so you are not serving the UI via cineast then. In that case, you would need to add the full prefix, i.e., `http://localhost:4567/objects/:o` to the configuration. And just to be clear, http://localhost:4567/thumbnails/i_0000001_1 returns an error?

**Comment by cribin** [comment]
Now the images are visible in the detail view. But the thumbnails link still returns the same error as above.

**Comment by lucaro** [comment]
I just realized that the [FileSystemThumbnailResolver]( https://github.com/vitrivr/cineast/blob/dev/cineast-api/src/main/java/org/vitrivr/cineast/api/rest/resolvers/FileSystemThumbnailResolver.java) didn't split the ids correctly. I'm a bit baffled by this, since nobody touched this thing in a long time, so I it must have been broken for a while. Can you do another pull and try again?

**Comment by cribin** [comment]
Thanks a lot for all the help. The images are now being displayed properly!

Best,

Ribin

**Comment by lucaro** [comment]
Great, I'll close this then.
