### ISSUE TITLE
Sorting contents in the UI according to a given score

### ISSUE THREAD

**Issue by cribin** [vitrivr/vitrivr-ng#45]
Hi,

I would like to add the ability to view the content sorted by a custom feature that I created. 
I succeeded in creating a custom feature and I can retrieve content from the database using the _RangeBooleanRetriever_.  
How can I rearrange how the content is presented in the UI? If I want to add additional UI elements, what is a good place to start, i.e. which files should I modify?

Best,

Ribin

**Comment by cribin** [comment]
Do you have any updates, on how to get started with sorting the content?

Best,

Ribin

**Comment by ppanopticon** [comment]
Hi

Sorting is always based on the score returned by Cineast and facilitated by a Pipe directly in the view. See, for example, the MiniGalleryView:

https://github.com/vitrivr/vitrivr-ng/blob/6bc9460c526374ac486e384ccb30e3b7e43a3c83/src/app/results/gallery/mini-gallery.component.html#L12

Of course you can create your own pipe implementation. See

- https://github.com/vitrivr/vitrivr-ng/blob/master/src/app/shared/pipes/containers/order-by-score.pipe.ts
- https://github.com/vitrivr/vitrivr-ng/blob/master/src/app/shared/pipes/containers/order-by-segment.pipe.ts

Ultimately, however, you somehow need to make sure, that Cineast returns the score produced by your feature.

**Comment by cribin** [comment]
Thanks for the detailed answer. I created a new class _SortedRangeBooleanRetriever_ extending the _BooleanRetriever_ class and created my own _getMatching_ method which returns a _SegmentScoreElement_ with the aesthetic score as input. How do I tell vitrivr-ng to use the new class instead of the _RangeBooleanRetriever?_ Previously I simply defined RANGE  in the config file of vitrivr-ng.

**Comment by lucaro** [comment]
You don't need to tell the UI anything about the features, they are completely handled by cineast. Just use your new feature instead of the previous one in the configuration.

**Comment by cribin** [comment]
I did as you suggested and replaced my _RangeBooleanRetriever_ with the new class, but upon debugging, while querying from the UI, the new code never gets executed.

[config-files.zip](https://github.com/vitrivr/vitrivr-ng/files/5306997/config-files.zip)

**Comment by cribin** [comment]
Thanks sorting the images worked. How would go about, if want to have an additional option to sort the scores ascending or descending? Maybe a ui element, which allows  me to select the sort option?

**Comment by lucaro** [comment]
The UI is not designed to support this, since there was never the need to show the 'worst' results at the top. If you wanted to implement such a functionality, you would need to extend the OrderByScorePipe as @ppanopticon pointed out in an earlier comment.

**Comment by cribin** [comment]
I want to create a UI element(like a dropdown box) that allows the user to select the sorting option directly above the slider, for the Range Query. Then I want to pass the selected sorting option as an input to the _OrderByScorePipe_. Since I'm not too familiar with Angular, could you provide some starting points and guides on how to achieve this?

Best,

Ribin

**Comment by lucaro** [comment]
You will need to create some Observables, which you can pass as an additional parameter to the sorting mechanism. For details on how to do any of this, it's probably best to consult the official Angular documentation.
