### ISSUE TITLE
Showing image feature in detail view.

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/vitrivr-ng#52]
Dear devs,

I want to display certain features in the object detail view. Let's say I have a feature _my_custom_feature_ extracted to the database for an image. Now, when I click on the image, I want to show the value of _my_custom_feature_ in the details view. Given an image, how can I access its _my_custom_feature_ value from vitrivr-ng?

Best,

Ribin

**Comment by lucaro** [comment]
There's currently no way to exactly what you want. The closest thing would be to store the information you want to display as metadata.

**Comment by RibinMTC** [comment]
In that case could you explain how vitrivr-ng communicates with cineast? If for example, I want to get a simple string from cineast, where and how would I do this in vitrivr-ng? As I'm not too familiar with angular, it would be great if you could point me towards an example class/file on how to do this.

**Comment by silvanheller** [comment]
Hey, I'm not sure how time-critical this is, but we currently have contributors (@cristinailli @mpas97) working on this. You can check out #50 which is currently under review. There is a corresponding PR on the Cineast side: https://github.com/vitrivr/cineast/pull/151. This adds (among other things) the ability to display tags and OCR data for an object / segment, so you might find inspiration there. 
I can't give you a timeline for when that PR will be merged as it is part of a larger ongoing project. If you need it very soon, we might be able to prioritize this.
I'm closing the Issue in the meantime.
