### ISSUE TITLE
Range Slider with Floating Point Values

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/vitrivr-ng#56]
Dear devs,

Is it possible to have the Range slider with floating-point values( for example in the range between 0 and 1)?

Best,

Ribin

**Comment by lucaro** [comment]
The sliders are provided by the material library for the angular framework, (see: https://material.angular.io/components/slider/overview) and their exact functionality is hence unrelated to vitrivr. Please have a look at the documentation before opening issues.

**Comment by RibinMTC** [comment]
Thanks for the link. But when I try to add a step value in the config file, the step still remains 1. So do I need to modify the vitrivr -code (i.e. _vitrivr-ng/src/app/query/containers/bool/bool-attribute.ts_) in order to get the desired functionality?

**Comment by silvanheller** [comment]
Yes, probably. Some of the sliders are implemented using a slider library since angular does not have sliders with a min and a max value in the standard library.

**Comment by RibinMTC** [comment]
Thanks by modifying the class I could achieve the desired functionality.
