### ISSUE TITLE
OpenAPI Cleanup

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-ng#58]
After merge of https://github.com/vitrivr/cineast/pull/161 and https://github.com/vitrivr/cineast/pull/162 , as well as #57 and #54 a holistic review and cleanup of the REST api is due.

In particular, reviewing the OpenApi Specification (OAS) of Cineast and the process on how it is included in vitrivr-ng (see https://github.com/vitrivr/vitrivr-ng/pull/54 as well as enforcinig consistency in naming of endpoints:

- [ ] Review OAS client code generation process

Shall be resolved in coordination with https://github.com/vitrivr/cineast/issues/163

**Comment by silvanheller** [comment]
The biggest and most relevant changes from vitrivr/cineast#161 and #57 w.r.t API extensions have been merged into dev, so this issue is ready to be tackled

**Comment by sauterl** [comment]
I will tackle this in accordance to https://github.com/vitrivr/cineast/issues/163

**Comment by sauterl** [comment]
Frontend related updates whenever the discussion https://github.com/vitrivr/cineast/discussions/176 comes to a conclusion. Closing this for now as it isn't relevant anymore
