### ISSUE TITLE
Highlight which view is currently active

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#66]
We got as feedback during the evaluation of @cristinailli that users would like some sort of indicator which view (mini-gallery, list) is active

**Comment by chinmaym07** [comment]
Hey @silvanheller .. I want to contribute to this project .
Can I work on this ?
What probable solution you want to be implemented for highlighting active views ?

**Comment by silvanheller** [comment]
Hey @chinmaym07 sure, feel free to fork the repository and create a PR. 

Currently, we're using simple hyperlinks rendered as `<mat-icon>` in `app.component.html` to switch between views. These would ideally be styled differently depending on the active view. There are multiple ways to implement this, for example the Material Design guide suggests [changing the opacity](https://material.io/design/iconography/system-icons.html#color) or you could switch the hyperlinks to [Buttons](https://material.angular.io/components/button/examples) and then do something with the button styling.

Feel free to come up with something that you think looks good and we'll have a look!

**Comment by chinmaym07** [comment]
@silvanheller Can you please help me out . I have completely setup the vitrivr-ng & completely able run the UI. 
 I am facing issue in setting up Cineast & Cottontaildb as they both are required for complete setup.

**Comment by silvanheller** [comment]
Are you following the guide at https://vitrivr.org/getting_started.html? If so, the best place to report issues is either via a separate issue on Github or to visit our slack channel at vitrivr.slack.com and ask for help there.

**Comment by chinmaym07** [comment]
Yes I am following the guide . I think I don't have an invitation to slack workspace that's why not able to join.
