### ISSUE TITLE
Handle configuration errors in a more user-friendly manner

### ISSUE THREAD

**Issue by lucaro** [vitrivr/vitrivr-ng#68]
When something goes wrong during the loading of the config, there is an exception which is shown in the console but no other indication to the user that something went wrong. This might be confusing, since it then also defaults to an internal config which might be very different from what the user intended. It would be great to add some more user-friendly indicator in case a config cannot be loaded and the default is used instead.

**Comment by silvanheller** [comment]
I have two ideas: We could add a red dot similarly to what happens if you're not logged into DRES or we could add a popup which you have to dismiss.

**Comment by lucaro** [comment]
I like the popup, it is intrusive enough that you won't miss it but not so intrusive as to prevent you from using the UI
