### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by Liuhaai** [vitrivr/vitrivr-ng#72]
Hi, I am a newer to Vitrivr. After all dependencies installed, there is a error when I try to start the server using `ng serve`. Both Cineast and Cottontaildb are running at background normally.

> Error: openapi/cineast/model/queryConfig.ts:12:21 - error TS2307: Cannot find module './set' or its corresponding type declarations.
12 import { Set } from './set';

**Comment by silvanheller** [comment]
Hi @Liuhaai, thanks for reporting your issue. You do not need to regenerate the OpenAPI Bindings, they are already present. I've updated the documentation to reflect that, thanks for bringing up the issue! 

In your case, you can simply discard the local changes by running `git fetch` and then `git reset --hard origin/master`

**Comment by Liuhaai** [comment]
> Hi @Liuhaai, thanks for reporting your issue. You do not need to regenerate the OpenAPI Bindings, they are already present. I've updated the documentation to reflect that, thanks for bringing up the issue!
> 
> In your case, you can simply discard the local changes by running `git fetch` and then `git reset --hard origin/master`

Hello @silvanheller, Thanks for quick response. I tried [the setup tutorials](https://github.com/vitrivr/vitrivr-ng/wiki). There are errors when building Angular files.

> Error: ./src/app/shared/util/m3d-file-loader.util.ts 10:15-29
"export 'Geometry' (imported as 'THREE') was not found in 'three'
Error: ./src/app/shared/util/m3d-file-loader.util.ts 35:37-51
"export 'Geometry' (imported as 'THREE') was not found in 'three'
Error: ./src/app/shared/util/m3d-file-loader.util.ts 40:49-63
"export 'Geometry' (imported as 'THREE') was not found in 'three'
Error: ./src/app/shared/util/m3d-file-loader.util.ts 75:44-58
"export 'Geometry' (imported as 'THREE') was not found in 'three'

**Comment by silvanheller** [comment]
At which command do these errors occur? And can you provide us with the output of `git status`

**Comment by Liuhaai** [comment]
I cloned vitrivr-ng from scratch, installed project's dependencies, and started the server.
```
git clone https://github.com/vitrivr/vitrivr-ng.git
cd vitrivr-ng
npm install
ng serve
```
The error happened at the last step `ng serve`
Here is the print result of `git status`:

> On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package-lock.json
        modified:   package.json
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by silvanheller** [comment]
Can you reset the changes to package.json using `git restore package.json` and then run `npm install` again

**Comment by Liuhaai** [comment]
> Can you reset the changes to package.json using `git restore package.json` and then run `npm install` again

Thanks for help. It works!
