### ISSUE TITLE
Text Categories for VBS 2019 and Beyond

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/vitrivr-ng#8]
We need to add the following categories:
- Audio
- Captioning (NN Captioning)

For flexibility, would it be possible to have the list of text categories configurable? I'd suggest that the config has an array like ["Text on Screen": "text", "Subtitles": "subtitles"] where the key is the text which appears and the value is the category sent to cineast (or introduce objects per element with i.e a flag which makes the boxes ticked by default).
This would give us maximum flexibility in the future and eases load on the UI development side, especially since different datasets will want different categories.

**Comment by ppanopticon** [comment]
Done! 

Best effort... ;-)

**Comment by silvanheller** [comment]
Works, thank you!
