### ISSUE TITLE
Bug: Uncaught TypeError: ng.probe is not a function

### ISSUE THREAD

**Issue by singaltanmay** [vitrivr/vitrivr-ng#83]
I on the latest commit of the dev branch and am getting an infinite stream of this error filling up my console. This error stops occurring when I am outside the window but as soon as my mouse even hovers over an angular component, this error start filling up the console.

![image](https://user-images.githubusercontent.com/31047659/126480109-90011199-6abd-4423-804e-b4859b5845e4.png)

`Uncaught TypeError: ng.probe is not a function`
`    isDebugMode ng-validate.js:1`
`    l ng-validate.js:1`
`    e ng-validate.js:1`
`    invoke zone-evergreen.js:364`
`    runGuarded zone-evergreen.js:133`
`    wrap zone-evergreen.js:117`

**Comment by silvanheller** [comment]
Closing as not reproducible
